import { UserProfile } from '../context/AuthContext';

export const MOCK_USERS: Record<'SYSTEM_ADMIN' | 'LANDLORD' | 'TENANT', UserProfile> = {
  SYSTEM_ADMIN: {
    id: 'mock-admin-001',
    email: 'admin@notify.test',
    phone: '+250780000001',
    first_name: 'Notify',
    last_name: 'Administrator',
    role: 'SYSTEM_ADMIN',
    language: 'en',
    status: 'ACTIVE',
  },
  LANDLORD: {
    id: 'mock-landlord-001',
    email: 'landlord@notify.test',
    phone: '+250780000002',
    first_name: 'Test',
    last_name: 'Landlord',
    role: 'LANDLORD',
    language: 'en',
    status: 'ACTIVE',
    landlord_profile: {
      id: 'mock-lp-001',
      business_type: 'COMPANY',
      business_name: 'Notify Dev Properties Ltd',
      address: 'KN 5 Ave, Plot 12',
      district: 'Nyarugenge',
      city: 'Kigali',
    },
  },
  TENANT: {
    id: 'mock-tenant-001',
    email: 'tenant@notify.test',
    phone: '+250780000003',
    first_name: 'Test',
    last_name: 'Tenant',
    role: 'TENANT',
    language: 'en',
    status: 'ACTIVE',
    tenant_profile: {
      id: 'mock-tp-001',
      national_id: '1199580012345678',
      occupation: 'Software Engineer',
    },
  },
};

export const MOCK_TOKENS = {
  SYSTEM_ADMIN: 'mock_token_SYSTEM_ADMIN',
  LANDLORD: 'mock_token_LANDLORD',
  TENANT: 'mock_token_TENANT',
};

/**
 * Check if mock auth is explicitly disabled via localStorage toggle.
 */
export function isMockAuthDisabled(): boolean {
  return localStorage.getItem('notify_disable_mock_auth') === 'true';
}

/**
 * Disable mock auth completely (restores pure production authentication mode).
 */
export function disableMockAuth(): void {
  localStorage.setItem('notify_disable_mock_auth', 'true');
}

/**
 * Re-enable mock auth for local testing.
 */
export function enableMockAuth(): void {
  localStorage.removeItem('notify_disable_mock_auth');
}

/**
 * Check if a given token is a mock token.
 */
export function isMockToken(token: string | null): boolean {
  if (!token || isMockAuthDisabled()) return false;
  return token.startsWith('mock_token_');
}

/**
 * Get mock user profile corresponding to a mock token.
 */
export function getMockUserByToken(token: string): UserProfile | null {
  if (isMockAuthDisabled()) return null;
  if (token === MOCK_TOKENS.SYSTEM_ADMIN) return MOCK_USERS.SYSTEM_ADMIN;
  if (token === MOCK_TOKENS.LANDLORD) return MOCK_USERS.LANDLORD;
  if (token === MOCK_TOKENS.TENANT) return MOCK_USERS.TENANT;
  return null;
}

/**
 * Match email to a mock profile if using mock login.
 */
export function getMockUserByEmail(email: string): UserProfile | null {
  if (isMockAuthDisabled()) return null;
  const normalized = email.trim().toLowerCase();
  if (normalized === 'admin@notify.test' || normalized === 'admin@notify.rw') {
    return MOCK_USERS.SYSTEM_ADMIN;
  }
  if (normalized === 'landlord@notify.test' || normalized === 'landlord@notify.rw') {
    return MOCK_USERS.LANDLORD;
  }
  if (normalized === 'tenant@notify.test' || normalized === 'tenant@notify.rw') {
    return MOCK_USERS.TENANT;
  }
  return null;
}

// ==========================================
// MOCK DATA FOR API DASHBOARDS (PHASE 2)
// ==========================================

export const MOCK_PROPERTIES: any[] = [
  {
    id: 'prop-heights',
    name: 'Notify Heights',
    property_type: 'APARTMENT',
    description: 'Modern residential apartment complex in Gasabo with premium amenities.',
    address: 'KG 14 Ave, Plot 88',
    district: 'Gasabo',
    sector: 'Kacyiru',
    status: 'ACTIVE',
    total_units: 8,
    occupied_units: 6,
    vacant_units: 2,
    expected_monthly_rent: 2450000,
    landlord_id: 'mock-lp-001',
  },
  {
    id: 'prop-101',
    name: 'Notify Commercial Complex',
    property_type: 'COMMERCIAL',
    description: 'Modern commercial complex in downtown Kigali with retail and office spaces',
    address: 'KN 5 Ave, Plot 12',
    district: 'Nyarugenge',
    sector: 'Nyarugenge',
    status: 'ACTIVE',
    total_units: 3,
    occupied_units: 2,
    vacant_units: 1,
    expected_monthly_rent: 1300000,
    landlord_id: 'mock-lp-001',
  },
];

export const MOCK_UNITS: any[] = [
  // Units for Notify Heights
  {
    id: 'unit-a101',
    property_id: 'prop-heights',
    unit_number: 'A-101',
    floor: 1,
    unit_type: '2 Bedroom',
    bedrooms: 2,
    bathrooms: 1,
    monthly_rent: 350000,
    currency: 'RWF',
    status: 'OCCUPIED',
    description: '1st floor apartment, street view',
    current_tenant_name: 'Eric Mugisha',
    current_tenant_id: 'tenant-102',
    lease_status: 'EXPIRING_SOON',
    lease_end_date: '2026-08-31',
  },
  {
    id: 'unit-a102',
    property_id: 'prop-heights',
    unit_number: 'A-102',
    floor: 1,
    unit_type: '2 Bedroom',
    bedrooms: 2,
    bathrooms: 2,
    monthly_rent: 350000,
    currency: 'RWF',
    status: 'OCCUPIED',
    description: '1st floor apartment, garden balcony',
    current_tenant_name: 'Test Tenant',
    current_tenant_id: 'mock-tenant-001',
    lease_status: 'ACTIVE',
    lease_end_date: '2027-12-31',
  },
  {
    id: 'unit-a103',
    property_id: 'prop-heights',
    unit_number: 'A-103',
    floor: 1,
    unit_type: '1 Bedroom',
    bedrooms: 1,
    bathrooms: 1,
    monthly_rent: 280000,
    currency: 'RWF',
    status: 'OCCUPIED',
    description: 'Compact studio flat',
    current_tenant_name: 'Divine Uwase',
    current_tenant_id: 'tenant-103',
    lease_status: 'EXPIRING_SOON',
    lease_end_date: '2026-09-05',
  },
  {
    id: 'unit-a201',
    property_id: 'prop-heights',
    unit_number: 'A-201',
    floor: 2,
    unit_type: '3 Bedroom Penthouse',
    bedrooms: 3,
    bathrooms: 2,
    monthly_rent: 500000,
    currency: 'RWF',
    status: 'OCCUPIED',
    description: 'Spacious penthouse with terrace',
    current_tenant_name: 'Patrick Bizimana',
    current_tenant_id: 'tenant-104',
    lease_status: 'EXPIRED',
    lease_end_date: '2025-12-31',
  },
  {
    id: 'unit-a202',
    property_id: 'prop-heights',
    unit_number: 'A-202',
    floor: 2,
    unit_type: '2 Bedroom',
    bedrooms: 2,
    bathrooms: 2,
    monthly_rent: 380000,
    currency: 'RWF',
    status: 'OCCUPIED',
    description: '2nd floor unit with open floor plan',
    current_tenant_name: 'Aline Mutesi',
    current_tenant_id: 'tenant-105',
    lease_status: 'ACTIVE',
    lease_end_date: '2027-06-30',
  },
  {
    id: 'unit-a203',
    property_id: 'prop-heights',
    unit_number: 'A-203',
    floor: 2,
    unit_type: '2 Bedroom',
    bedrooms: 2,
    bathrooms: 1,
    monthly_rent: 340000,
    currency: 'RWF',
    status: 'OCCUPIED',
    description: 'Cozy 2-bedroom space',
    current_tenant_name: 'Jean-Paul Ndayishimiye',
    current_tenant_id: 'tenant-106',
    lease_status: 'ACTIVE',
    lease_end_date: '2027-04-15',
  },
  {
    id: 'unit-b101',
    property_id: 'prop-heights',
    unit_number: 'B-101',
    floor: 1,
    unit_type: '1 Bedroom',
    bedrooms: 1,
    bathrooms: 1,
    monthly_rent: 250000,
    currency: 'RWF',
    status: 'VACANT',
    description: 'Newly renovated 1-bedroom flat ready for move in',
  },
  {
    id: 'unit-b102',
    property_id: 'prop-heights',
    unit_number: 'B-102',
    floor: 1,
    unit_type: '1 Bedroom',
    bedrooms: 1,
    bathrooms: 1,
    monthly_rent: 250000,
    currency: 'RWF',
    status: 'VACANT',
    description: 'Ground floor corner flat',
  },
  // Units for Notify Commercial Complex
  {
    id: 'unit-101',
    property_id: 'prop-101',
    unit_number: '101',
    floor: 1,
    unit_type: 'Retail Shop',
    monthly_rent: 250000,
    currency: 'RWF',
    status: 'OCCUPIED',
    description: 'Ground floor retail unit with street view',
    current_tenant_name: 'Claude Nshimyumuremyi',
    current_tenant_id: 'tenant-107',
    lease_status: 'EXPIRING_SOON',
    lease_end_date: '2026-08-25',
  },
  {
    id: 'unit-102',
    property_id: 'prop-101',
    unit_number: '102',
    floor: 1,
    unit_type: 'Office Suite',
    monthly_rent: 400000,
    currency: 'RWF',
    status: 'VACANT',
    description: 'Spacious office suite with modern glass partition',
  },
  {
    id: 'unit-201',
    property_id: 'prop-101',
    unit_number: '201',
    floor: 2,
    unit_type: 'Executive Office',
    monthly_rent: 650000,
    currency: 'RWF',
    status: 'OCCUPIED',
    description: 'Corner office with panoramic city view',
    current_tenant_name: 'Tech Hub Ltd',
    current_tenant_id: 'tenant-108',
    lease_status: 'ACTIVE',
    lease_end_date: '2028-01-31',
  },
];

export const MOCK_TENANTS: any[] = [
  {
    id: 'mock-tenant-001',
    first_name: 'Test',
    last_name: 'Tenant',
    email: 'tenant@notify.test',
    phone: '+250780000003',
    preferred_language: 'EN',
    national_id: '1199580012345678',
    occupation: 'Software Engineer',
    property_id: 'prop-heights',
    property_name: 'Notify Heights',
    unit_id: 'unit-a102',
    unit_number: 'A-102',
    monthly_rent: 350000,
    currency: 'RWF',
    status: 'ACTIVE',
    lease_status: 'ACTIVE',
    lease_end_date: '2027-12-31',
    tenancy_start_date: '2026-01-01',
    history: [
      {
        id: 'hist-001',
        property_name: 'Gasabo Terrace Apartments',
        unit_number: 'G-105',
        start_date: '2023-06-01',
        end_date: '2025-12-15',
        monthly_rent: 300000,
        currency: 'RWF',
        status: 'COMPLETED',
      },
    ],
  },
  {
    id: 'tenant-102',
    first_name: 'Eric',
    last_name: 'Mugisha',
    email: 'eric.mugisha@notify.test',
    phone: '+250788112233',
    preferred_language: 'RW',
    national_id: '1199280044556677',
    occupation: 'Accountant',
    property_id: 'prop-heights',
    property_name: 'Notify Heights',
    unit_id: 'unit-a101',
    unit_number: 'A-101',
    monthly_rent: 350000,
    currency: 'RWF',
    status: 'ACTIVE',
    lease_status: 'EXPIRING_SOON',
    lease_end_date: '2026-08-31',
    tenancy_start_date: '2025-09-01',
    history: [],
  },
  {
    id: 'tenant-103',
    first_name: 'Divine',
    last_name: 'Uwase',
    email: 'divine.uwase@notify.test',
    phone: '+250788998877',
    preferred_language: 'FR',
    national_id: '1199880022334411',
    occupation: 'Architect',
    property_id: 'prop-heights',
    property_name: 'Notify Heights',
    unit_id: 'unit-a103',
    unit_number: 'A-103',
    monthly_rent: 280000,
    currency: 'RWF',
    status: 'ACTIVE',
    lease_status: 'EXPIRING_SOON',
    lease_end_date: '2026-09-05',
    tenancy_start_date: '2025-09-10',
    history: [],
  },
  {
    id: 'tenant-104',
    first_name: 'Patrick',
    last_name: 'Bizimana',
    email: 'patrick.bizimana@notify.test',
    phone: '+250783334455',
    preferred_language: 'EN',
    national_id: '1199080099887766',
    occupation: 'Business Consultant',
    property_id: 'prop-heights',
    property_name: 'Notify Heights',
    unit_id: 'unit-a201',
    unit_number: 'A-201',
    monthly_rent: 500000,
    currency: 'RWF',
    status: 'ACTIVE',
    lease_status: 'EXPIRED',
    lease_end_date: '2025-12-31',
    tenancy_start_date: '2024-01-01',
    history: [],
  },
  {
    id: 'tenant-107',
    first_name: 'Claude',
    last_name: 'Nshimyumuremyi',
    email: 'claude.n@notify.test',
    phone: '+250785556677',
    preferred_language: 'EN',
    national_id: '1199480077665544',
    occupation: 'Retailer',
    property_id: 'prop-101',
    property_name: 'Notify Commercial Complex',
    unit_id: 'unit-101',
    unit_number: '101',
    monthly_rent: 250000,
    currency: 'RWF',
    status: 'ACTIVE',
    lease_status: 'EXPIRING_SOON',
    lease_end_date: '2026-08-25',
    tenancy_start_date: '2025-09-01',
    history: [],
  },
];

export const MOCK_LEASES: any[] = [
  {
    id: 'lease-101',
    tenancy_id: 'tenancy-101',
    tenant_id: 'mock-tenant-001',
    tenant_name: 'Test Tenant',
    property_id: 'prop-heights',
    property_name: 'Notify Heights',
    unit_id: 'unit-a102',
    unit_number: 'A-102',
    start_date: '2026-01-01',
    end_date: '2027-12-31',
    monthly_rent: 350000,
    security_deposit: 350000,
    payment_due_day: 5,
    late_fee: 15000,
    currency: 'RWF',
    status: 'ACTIVE',
    days_remaining: 504,
    notes: 'Standard 24-month commercial/residential lease.',
    has_signed_document: true,
    compliance_status: 'COMPLETE',
    compliance_notes: 'All legal requirements met. Signed agreement on file.',
    agreement_document: {
      id: 'doc-lease-101',
      lease_id: 'lease-101',
      tenant_id: 'mock-tenant-001',
      tenant_name: 'Test Tenant',
      property_id: 'prop-heights',
      property_name: 'Notify Heights',
      unit_id: 'unit-a102',
      unit_number: 'A-102',
      doc_type: 'LEASE_AGREEMENT',
      document_name: 'Notify Heights Unit A-102 Residential Lease Agreement',
      file_name: 'Notify_Heights_A102_Lease_Agreement_Signed.pdf',
      file_type: 'application/pdf',
      file_size: 2450000,
      storage_path: 'leases/lease-101/agreement/v2/Notify_Heights_A102_Lease_Agreement_Signed.pdf',
      uploaded_by: 'Notify Properties Ltd (Landlord)',
      uploaded_by_role: 'LANDLORD',
      uploaded_at: '2026-01-02T10:30:00Z',
      version: 2,
      status: 'ACTIVE',
      is_verified: true,
      history: [
        {
          version: 1,
          document_name: 'Notify Heights Unit A-102 Draft Agreement',
          file_name: 'Notify_Heights_A102_Draft_v1.pdf',
          file_type: 'application/pdf',
          file_size: 2100000,
          storage_path: 'leases/lease-101/agreement/v1/Notify_Heights_A102_Draft_v1.pdf',
          uploaded_by: 'Notify Properties Ltd (Landlord)',
          uploaded_by_role: 'LANDLORD',
          uploaded_at: '2025-12-28T14:15:00Z',
          version_notes: 'Initial unsigned draft template with standard indemnity clauses.',
          status: 'SUPERSEDED',
        },
        {
          version: 2,
          document_name: 'Notify Heights Unit A-102 Residential Lease Agreement',
          file_name: 'Notify_Heights_A102_Lease_Agreement_Signed.pdf',
          file_type: 'application/pdf',
          file_size: 2450000,
          storage_path: 'leases/lease-101/agreement/v2/Notify_Heights_A102_Lease_Agreement_Signed.pdf',
          uploaded_by: 'Notify Properties Ltd (Landlord)',
          uploaded_by_role: 'LANDLORD',
          uploaded_at: '2026-01-02T10:30:00Z',
          version_notes: 'Countersigned official lease agreement by landlord and tenant with verified ID stamps.',
          status: 'ACTIVE',
        },
      ],
    },
    document_history: [
      {
        version: 1,
        document_name: 'Notify Heights Unit A-102 Draft Agreement',
        file_name: 'Notify_Heights_A102_Draft_v1.pdf',
        file_type: 'application/pdf',
        file_size: 2100000,
        storage_path: 'leases/lease-101/agreement/v1/Notify_Heights_A102_Draft_v1.pdf',
        uploaded_by: 'Notify Properties Ltd (Landlord)',
        uploaded_by_role: 'LANDLORD',
        uploaded_at: '2025-12-28T14:15:00Z',
        version_notes: 'Initial unsigned draft template with standard indemnity clauses.',
        status: 'SUPERSEDED',
      },
      {
        version: 2,
        document_name: 'Notify Heights Unit A-102 Residential Lease Agreement',
        file_name: 'Notify_Heights_A102_Lease_Agreement_Signed.pdf',
        file_type: 'application/pdf',
        file_size: 2450000,
        storage_path: 'leases/lease-101/agreement/v2/Notify_Heights_A102_Lease_Agreement_Signed.pdf',
        uploaded_by: 'Notify Properties Ltd (Landlord)',
        uploaded_by_role: 'LANDLORD',
        uploaded_at: '2026-01-02T10:30:00Z',
        version_notes: 'Countersigned official lease agreement by landlord and tenant with verified ID stamps.',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'lease-30d',
    tenancy_id: 'tenancy-30d',
    tenant_id: 'tenant-103',
    tenant_name: 'Divine Uwase',
    property_id: 'prop-heights',
    property_name: 'Notify Heights',
    unit_id: 'unit-a103',
    unit_number: 'A-103',
    start_date: '2025-09-13',
    end_date: '2026-09-13',
    monthly_rent: 280000,
    security_deposit: 280000,
    payment_due_day: 5,
    late_fee: 10000,
    currency: 'RWF',
    status: 'EXPIRING_SOON',
    days_remaining: 30,
    notes: '30-Day milestone notice generated. Awaiting response on 12-month extension offer.',
    has_signed_document: true,
    compliance_status: 'COMPLETE',
    agreement_document: {
      id: 'doc-lease-30d',
      lease_id: 'lease-30d',
      tenant_id: 'tenant-103',
      tenant_name: 'Divine Uwase',
      property_id: 'prop-heights',
      property_name: 'Notify Heights',
      unit_id: 'unit-a103',
      unit_number: 'A-103',
      doc_type: 'LEASE_AGREEMENT',
      document_name: 'Divine_Uwase_Lease_Agreement_Unit_A103.pdf',
      file_name: 'Divine_Uwase_Lease_Agreement_Unit_A103.pdf',
      file_type: 'application/pdf',
      file_size: 1850000,
      storage_path: 'leases/lease-30d/agreement/v1/Divine_Uwase_Lease_Agreement_Unit_A103.pdf',
      uploaded_by: 'Notify Properties Ltd',
      uploaded_by_role: 'LANDLORD',
      uploaded_at: '2025-09-10T09:00:00Z',
      version: 1,
      status: 'ACTIVE',
      is_verified: true,
      history: [
        {
          version: 1,
          document_name: 'Divine_Uwase_Lease_Agreement_Unit_A103.pdf',
          file_name: 'Divine_Uwase_Lease_Agreement_Unit_A103.pdf',
          file_type: 'application/pdf',
          file_size: 1850000,
          storage_path: 'leases/lease-30d/agreement/v1/Divine_Uwase_Lease_Agreement_Unit_A103.pdf',
          uploaded_by: 'Notify Properties Ltd',
          uploaded_by_role: 'LANDLORD',
          uploaded_at: '2025-09-10T09:00:00Z',
          version_notes: 'Initial registered 1-year tenancy contract.',
          status: 'ACTIVE',
        },
      ],
    },
    document_history: [
      {
        version: 1,
        document_name: 'Divine_Uwase_Lease_Agreement_Unit_A103.pdf',
        file_name: 'Divine_Uwase_Lease_Agreement_Unit_A103.pdf',
        file_type: 'application/pdf',
        file_size: 1850000,
        storage_path: 'leases/lease-30d/agreement/v1/Divine_Uwase_Lease_Agreement_Unit_A103.pdf',
        uploaded_by: 'Notify Properties Ltd',
        uploaded_by_role: 'LANDLORD',
        uploaded_at: '2025-09-10T09:00:00Z',
        version_notes: 'Initial registered 1-year tenancy contract.',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'lease-14d',
    tenancy_id: 'tenancy-14d',
    tenant_id: 'tenant-102',
    tenant_name: 'Eric Mugisha',
    property_id: 'prop-heights',
    property_name: 'Notify Heights',
    unit_id: 'unit-a101',
    unit_number: 'A-101',
    start_date: '2025-08-28',
    end_date: '2026-08-28',
    monthly_rent: 350000,
    security_deposit: 350000,
    payment_due_day: 5,
    late_fee: 15000,
    currency: 'RWF',
    status: 'EXPIRING_SOON',
    days_remaining: 14,
    notes: '14-Day reminder sent. Tenant verbal confirmation of renewal pending signature.',
    has_signed_document: true,
    compliance_status: 'COMPLETE',
    agreement_document: {
      id: 'doc-lease-14d',
      lease_id: 'lease-14d',
      tenant_id: 'tenant-102',
      tenant_name: 'Eric Mugisha',
      property_id: 'prop-heights',
      property_name: 'Notify Heights',
      unit_id: 'unit-a101',
      unit_number: 'A-101',
      doc_type: 'LEASE_AGREEMENT',
      document_name: 'Eric_Mugisha_Tenancy_Contract_A101.pdf',
      file_name: 'Eric_Mugisha_Tenancy_Contract_A101.pdf',
      file_type: 'application/pdf',
      file_size: 3200000,
      storage_path: 'leases/lease-14d/agreement/v1/Eric_Mugisha_Tenancy_Contract_A101.pdf',
      uploaded_by: 'Notify Properties Ltd',
      uploaded_by_role: 'LANDLORD',
      uploaded_at: '2025-08-25T11:00:00Z',
      version: 1,
      status: 'ACTIVE',
      is_verified: true,
      history: [
        {
          version: 1,
          document_name: 'Eric_Mugisha_Tenancy_Contract_A101.pdf',
          file_name: 'Eric_Mugisha_Tenancy_Contract_A101.pdf',
          file_type: 'application/pdf',
          file_size: 3200000,
          storage_path: 'leases/lease-14d/agreement/v1/Eric_Mugisha_Tenancy_Contract_A101.pdf',
          uploaded_by: 'Notify Properties Ltd',
          uploaded_by_role: 'LANDLORD',
          uploaded_at: '2025-08-25T11:00:00Z',
          version_notes: 'Standard signed residential agreement with inventory checklist.',
          status: 'ACTIVE',
        },
      ],
    },
    document_history: [
      {
        version: 1,
        document_name: 'Eric_Mugisha_Tenancy_Contract_A101.pdf',
        file_name: 'Eric_Mugisha_Tenancy_Contract_A101.pdf',
        file_type: 'application/pdf',
        file_size: 3200000,
        storage_path: 'leases/lease-14d/agreement/v1/Eric_Mugisha_Tenancy_Contract_A101.pdf',
        uploaded_by: 'Notify Properties Ltd',
        uploaded_by_role: 'LANDLORD',
        uploaded_at: '2025-08-25T11:00:00Z',
        version_notes: 'Standard signed residential agreement with inventory checklist.',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'lease-7d',
    tenancy_id: 'tenancy-7d',
    tenant_id: 'tenant-107',
    tenant_name: 'Claude Nshimyumuremyi',
    property_id: 'prop-101',
    property_name: 'Notify Commercial Complex',
    unit_id: 'unit-101',
    unit_number: '101',
    start_date: '2025-08-21',
    end_date: '2026-08-21',
    monthly_rent: 250000,
    security_deposit: 250000,
    payment_due_day: 1,
    late_fee: 12000,
    currency: 'RWF',
    status: 'EXPIRING_SOON',
    days_remaining: 7,
    notes: '7-Day urgent reminder. Move-out checklist and renewal contract sent.',
    has_signed_document: true,
    compliance_status: 'COMPLETE',
    agreement_document: {
      id: 'doc-lease-7d',
      lease_id: 'lease-7d',
      tenant_id: 'tenant-107',
      tenant_name: 'Claude Nshimyumuremyi',
      property_id: 'prop-101',
      property_name: 'Notify Commercial Complex',
      unit_id: 'unit-101',
      unit_number: '101',
      doc_type: 'LEASE_AGREEMENT',
      document_name: 'Claude_N_Commercial_Lease_Unit101.docx',
      file_name: 'Claude_N_Commercial_Lease_Unit101.docx',
      file_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      file_size: 1420000,
      storage_path: 'leases/lease-7d/agreement/v1/Claude_N_Commercial_Lease_Unit101.docx',
      uploaded_by: 'Notify Properties Ltd',
      uploaded_by_role: 'LANDLORD',
      uploaded_at: '2025-08-20T16:00:00Z',
      version: 1,
      status: 'ACTIVE',
      is_verified: true,
      history: [
        {
          version: 1,
          document_name: 'Claude_N_Commercial_Lease_Unit101.docx',
          file_name: 'Claude_N_Commercial_Lease_Unit101.docx',
          file_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
          file_size: 1420000,
          storage_path: 'leases/lease-7d/agreement/v1/Claude_N_Commercial_Lease_Unit101.docx',
          uploaded_by: 'Notify Properties Ltd',
          uploaded_by_role: 'LANDLORD',
          uploaded_at: '2025-08-20T16:00:00Z',
          version_notes: 'Commercial lease agreement for retail unit 101.',
          status: 'ACTIVE',
        },
      ],
    },
    document_history: [
      {
        version: 1,
        document_name: 'Claude_N_Commercial_Lease_Unit101.docx',
        file_name: 'Claude_N_Commercial_Lease_Unit101.docx',
        file_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        file_size: 1420000,
        storage_path: 'leases/lease-7d/agreement/v1/Claude_N_Commercial_Lease_Unit101.docx',
        uploaded_by: 'Notify Properties Ltd',
        uploaded_by_role: 'LANDLORD',
        uploaded_at: '2025-08-20T16:00:00Z',
        version_notes: 'Commercial lease agreement for retail unit 101.',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'lease-3d',
    tenancy_id: 'tenancy-3d',
    tenant_id: 'tenant-105',
    tenant_name: 'Aline Mutesi',
    property_id: 'prop-heights',
    property_name: 'Notify Heights',
    unit_id: 'unit-a202',
    unit_number: 'A-202',
    start_date: '2025-08-17',
    end_date: '2026-08-17',
    monthly_rent: 380000,
    security_deposit: 380000,
    payment_due_day: 5,
    late_fee: 15000,
    currency: 'RWF',
    status: 'EXPIRING_SOON',
    days_remaining: 3,
    notes: 'Critical 3-day reminder dispatched to tenant and landlord.',
    has_signed_document: true,
    compliance_status: 'COMPLETE',
    agreement_document: {
      id: 'doc-lease-3d',
      lease_id: 'lease-3d',
      tenant_id: 'tenant-105',
      tenant_name: 'Aline Mutesi',
      property_id: 'prop-heights',
      property_name: 'Notify Heights',
      unit_id: 'unit-a202',
      unit_number: 'A-202',
      doc_type: 'LEASE_AGREEMENT',
      document_name: 'Aline_Mutesi_Signed_Lease_A202.pdf',
      file_name: 'Aline_Mutesi_Signed_Lease_A202.pdf',
      file_type: 'application/pdf',
      file_size: 2750000,
      storage_path: 'leases/lease-3d/agreement/v1/Aline_Mutesi_Signed_Lease_A202.pdf',
      uploaded_by: 'Notify Properties Ltd',
      uploaded_by_role: 'LANDLORD',
      uploaded_at: '2025-08-15T15:00:00Z',
      version: 1,
      status: 'ACTIVE',
      is_verified: true,
      history: [
        {
          version: 1,
          document_name: 'Aline_Mutesi_Signed_Lease_A202.pdf',
          file_name: 'Aline_Mutesi_Signed_Lease_A202.pdf',
          file_type: 'application/pdf',
          file_size: 2750000,
          storage_path: 'leases/lease-3d/agreement/v1/Aline_Mutesi_Signed_Lease_A202.pdf',
          uploaded_by: 'Notify Properties Ltd',
          uploaded_by_role: 'LANDLORD',
          uploaded_at: '2025-08-15T15:00:00Z',
          version_notes: 'Initial 1-year tenancy agreement signed with notary seal.',
          status: 'ACTIVE',
        },
      ],
    },
  },
  {
    id: 'lease-2d',
    tenancy_id: 'tenancy-2d',
    tenant_id: 'tenant-106',
    tenant_name: 'Jean-Paul Ndayishimiye',
    property_id: 'prop-heights',
    property_name: 'Notify Heights',
    unit_id: 'unit-a203',
    unit_number: 'A-203',
    start_date: '2025-08-16',
    end_date: '2026-08-16',
    monthly_rent: 340000,
    security_deposit: 340000,
    payment_due_day: 5,
    late_fee: 15000,
    currency: 'RWF',
    status: 'EXPIRING_SOON',
    days_remaining: 2,
    notes: '2-Day expiry alert. Deposit reconciliation sheet prepared.',
    has_signed_document: true,
    compliance_status: 'COMPLETE',
    agreement_document: {
      id: 'doc-lease-2d',
      lease_id: 'lease-2d',
      tenant_id: 'tenant-106',
      tenant_name: 'Jean-Paul Ndayishimiye',
      property_id: 'prop-heights',
      property_name: 'Notify Heights',
      unit_id: 'unit-a203',
      unit_number: 'A-203',
      doc_type: 'LEASE_AGREEMENT',
      document_name: 'JeanPaul_Ndayishimiye_Lease_A203.pdf',
      file_name: 'JeanPaul_Ndayishimiye_Lease_A203.pdf',
      file_type: 'application/pdf',
      file_size: 1980000,
      storage_path: 'leases/lease-2d/agreement/v1/JeanPaul_Ndayishimiye_Lease_A203.pdf',
      uploaded_by: 'Notify Properties Ltd',
      uploaded_by_role: 'LANDLORD',
      uploaded_at: '2025-08-14T10:00:00Z',
      version: 1,
      status: 'ACTIVE',
      is_verified: true,
      history: [
        {
          version: 1,
          document_name: 'JeanPaul_Ndayishimiye_Lease_A203.pdf',
          file_name: 'JeanPaul_Ndayishimiye_Lease_A203.pdf',
          file_type: 'application/pdf',
          file_size: 1980000,
          storage_path: 'leases/lease-2d/agreement/v1/JeanPaul_Ndayishimiye_Lease_A203.pdf',
          uploaded_by: 'Notify Properties Ltd',
          uploaded_by_role: 'LANDLORD',
          uploaded_at: '2025-08-14T10:00:00Z',
          version_notes: 'Original standard lease agreement for Unit A-203.',
          status: 'ACTIVE',
        },
      ],
    },
  },
  {
    id: 'lease-1d',
    tenancy_id: 'tenancy-1d',
    tenant_id: 'tenant-108',
    tenant_name: 'Tech Hub Ltd (Keza Marie)',
    property_id: 'prop-101',
    property_name: 'Notify Commercial Complex',
    unit_id: 'unit-201',
    unit_number: '201',
    start_date: '2025-08-15',
    end_date: '2026-08-15',
    monthly_rent: 650000,
    security_deposit: 650000,
    payment_due_day: 1,
    late_fee: 30000,
    currency: 'RWF',
    status: 'EXPIRING_SOON',
    days_remaining: 1,
    notes: 'Lease expires tomorrow! Final extension addendum scheduled for execution.',
    has_signed_document: true,
    compliance_status: 'COMPLETE',
    agreement_document: {
      id: 'doc-lease-1d',
      lease_id: 'lease-1d',
      tenant_id: 'tenant-108',
      tenant_name: 'Tech Hub Ltd (Keza Marie)',
      property_id: 'prop-101',
      property_name: 'Notify Commercial Complex',
      unit_id: 'unit-201',
      unit_number: '201',
      doc_type: 'LEASE_AGREEMENT',
      document_name: 'TechHub_Ltd_Commercial_Lease_Contract_Signed.pdf',
      file_name: 'TechHub_Ltd_Commercial_Lease_Contract_Signed.pdf',
      file_type: 'application/pdf',
      file_size: 4500000,
      storage_path: 'leases/lease-1d/agreement/v1/TechHub_Ltd_Commercial_Lease_Contract_Signed.pdf',
      uploaded_by: 'Notify Properties Ltd',
      uploaded_by_role: 'LANDLORD',
      uploaded_at: '2025-08-12T14:30:00Z',
      version: 1,
      status: 'ACTIVE',
      is_verified: true,
      history: [
        {
          version: 1,
          document_name: 'TechHub_Ltd_Commercial_Lease_Contract_Signed.pdf',
          file_name: 'TechHub_Ltd_Commercial_Lease_Contract_Signed.pdf',
          file_type: 'application/pdf',
          file_size: 4500000,
          storage_path: 'leases/lease-1d/agreement/v1/TechHub_Ltd_Commercial_Lease_Contract_Signed.pdf',
          uploaded_by: 'Notify Properties Ltd',
          uploaded_by_role: 'LANDLORD',
          uploaded_at: '2025-08-12T14:30:00Z',
          version_notes: 'Commercial lease for corporate suite with high-speed internet clause.',
          status: 'ACTIVE',
        },
      ],
    },
  },
  {
    id: 'lease-today',
    tenancy_id: 'tenancy-today',
    tenant_id: 'tenant-109',
    tenant_name: 'Samuel Kayiranga',
    property_id: 'prop-heights',
    property_name: 'Notify Heights',
    unit_id: 'unit-a104',
    unit_number: 'A-104',
    start_date: '2025-08-14',
    end_date: '2026-08-14',
    monthly_rent: 310000,
    security_deposit: 310000,
    payment_due_day: 5,
    late_fee: 15000,
    currency: 'RWF',
    status: 'EXPIRING_SOON',
    days_remaining: 0,
    notes: 'Lease expires TODAY. Handover or renewed signature required by 5:00 PM.',
    has_signed_document: true,
    compliance_status: 'COMPLETE',
    agreement_document: {
      id: 'doc-lease-today',
      lease_id: 'lease-today',
      tenant_id: 'tenant-109',
      tenant_name: 'Samuel Kayiranga',
      property_id: 'prop-heights',
      property_name: 'Notify Heights',
      unit_id: 'unit-a104',
      unit_number: 'A-104',
      doc_type: 'LEASE_AGREEMENT',
      document_name: 'Samuel_Kayiranga_Lease_A104.pdf',
      file_name: 'Samuel_Kayiranga_Lease_A104.pdf',
      file_type: 'application/pdf',
      file_size: 2150000,
      storage_path: 'leases/lease-today/agreement/v1/Samuel_Kayiranga_Lease_A104.pdf',
      uploaded_by: 'Notify Properties Ltd',
      uploaded_by_role: 'LANDLORD',
      uploaded_at: '2025-08-10T11:20:00Z',
      version: 1,
      status: 'ACTIVE',
      is_verified: true,
      history: [
        {
          version: 1,
          document_name: 'Samuel_Kayiranga_Lease_A104.pdf',
          file_name: 'Samuel_Kayiranga_Lease_A104.pdf',
          file_type: 'application/pdf',
          file_size: 2150000,
          storage_path: 'leases/lease-today/agreement/v1/Samuel_Kayiranga_Lease_A104.pdf',
          uploaded_by: 'Notify Properties Ltd',
          uploaded_by_role: 'LANDLORD',
          uploaded_at: '2025-08-10T11:20:00Z',
          version_notes: 'Standard 12-month agreement.',
          status: 'ACTIVE',
        },
      ],
    },
  },
  {
    id: 'lease-draft-01',
    tenancy_id: 'tenancy-draft-01',
    tenant_id: 'tenant-110',
    tenant_name: 'Honorine Ishimwe (Pending)',
    property_id: 'prop-heights',
    property_name: 'Notify Heights',
    unit_id: 'unit-a105',
    unit_number: 'A-105',
    start_date: '2026-09-01',
    end_date: '2027-08-31',
    monthly_rent: 360000,
    security_deposit: 360000,
    payment_due_day: 5,
    late_fee: 15000,
    currency: 'RWF',
    status: 'DRAFT',
    notes: 'Draft lease awaiting upload of countersigned agreement document before activation.',
    has_signed_document: false,
    compliance_status: 'INCOMPLETE',
    compliance_notes: 'Missing: Signed Lease Agreement. Upload signed copy to activate lease.',
  },
  {
    id: 'lease-expired',
    tenancy_id: 'tenancy-105',
    tenant_id: 'tenant-104',
    tenant_name: 'Patrick Bizimana',
    property_id: 'prop-heights',
    property_name: 'Notify Heights',
    unit_id: 'unit-a201',
    unit_number: 'A-201',
    start_date: '2024-01-01',
    end_date: '2025-12-31',
    monthly_rent: 500000,
    security_deposit: 500000,
    payment_due_day: 5,
    late_fee: 20000,
    currency: 'RWF',
    status: 'EXPIRED',
    days_remaining: -226,
    notes: 'Lease expired, month-to-month holdover.',
    has_signed_document: true,
    compliance_status: 'COMPLETE',
    agreement_document: {
      id: 'doc-lease-expired',
      lease_id: 'lease-expired',
      tenant_id: 'tenant-104',
      tenant_name: 'Patrick Bizimana',
      property_id: 'prop-heights',
      property_name: 'Notify Heights',
      unit_id: 'unit-a201',
      unit_number: 'A-201',
      doc_type: 'LEASE_AGREEMENT',
      document_name: 'Patrick_Bizimana_Historical_Lease_2024.pdf',
      file_name: 'Patrick_Bizimana_Historical_Lease_2024.pdf',
      file_type: 'application/pdf',
      file_size: 2600000,
      storage_path: 'leases/lease-expired/agreement/v1/Patrick_Bizimana_Historical_Lease_2024.pdf',
      uploaded_by: 'Notify Properties Ltd',
      uploaded_by_role: 'LANDLORD',
      uploaded_at: '2024-01-02T10:00:00Z',
      version: 1,
      status: 'ARCHIVED',
      is_verified: true,
      history: [
        {
          version: 1,
          document_name: 'Patrick_Bizimana_Historical_Lease_2024.pdf',
          file_name: 'Patrick_Bizimana_Historical_Lease_2024.pdf',
          file_type: 'application/pdf',
          file_size: 2600000,
          storage_path: 'leases/lease-expired/agreement/v1/Patrick_Bizimana_Historical_Lease_2024.pdf',
          uploaded_by: 'Notify Properties Ltd',
          uploaded_by_role: 'LANDLORD',
          uploaded_at: '2024-01-02T10:00:00Z',
          version_notes: 'Historical executed lease agreement (Expired).',
          status: 'ARCHIVED',
        },
      ],
    },
  },
];

export const MOCK_TENANCIES: any[] = [
  {
    id: 'tenancy-101',
    status: 'ACTIVE',
    start_date: '2026-01-01',
    end_date: '2027-12-31',
    tenant_id: 'mock-tenant-001',
    unit_id: 'unit-a102',
    property_id: 'prop-heights',
    unit: {
      id: 'unit-a102',
      unit_number: 'A-102',
      floor: 1,
      unit_type: '2 Bedroom',
      monthly_rent: 350000,
      currency: 'RWF',
      status: 'OCCUPIED',
      description: '1st floor apartment, garden balcony',
    },
    property: {
      id: 'prop-heights',
      name: 'Notify Heights',
      address: 'KG 14 Ave, Plot 88, Kacyiru, Kigali',
      district: 'Gasabo',
      property_type: 'APARTMENT',
    },
    landlord: {
      first_name: 'Test',
      last_name: 'Landlord',
      email: 'landlord@notify.test',
      phone: '+250780000002',
      business_name: 'Notify Dev Properties Ltd',
    },
  },
];

export const MOCK_INVITATIONS: any[] = [
  {
    id: 'inv-101',
    tenant_email: 'tenant@notify.test',
    tenant_phone: '+250780000003',
    property_id: 'prop-heights',
    property_name: 'Notify Heights',
    unit_id: 'unit-b101',
    unit_number: 'B-101',
    token: 'inv_demo_101',
    status: 'ACCEPTED',
    created_at: '2026-08-01T10:00:00Z',
    expires_at: '2026-08-15T10:00:00Z',
  },
  {
    id: 'inv-102',
    tenant_email: 'prospective@notify.test',
    tenant_phone: '+250780000005',
    property_id: 'prop-heights',
    property_name: 'Notify Heights',
    unit_id: 'unit-b102',
    unit_number: 'B-102',
    token: 'inv_demo_102',
    status: 'PENDING',
    created_at: '2026-08-10T14:30:00Z',
    expires_at: '2026-08-24T14:30:00Z',
  },
];

export const MOCK_ADMIN_STATS = {
  total_users: 148,
  total_landlords: 32,
  total_tenants: 115,
  total_properties: 45,
  total_units: 210,
  active_tenancies: 185,
  pending_invitations: 12,
  monthly_revenue_rwf: 42500000,
};

export const MOCK_ADMIN_USERS = [
  {
    id: 'usr-001',
    first_name: 'Notify',
    last_name: 'Administrator',
    email: 'admin@notify.test',
    role: 'SYSTEM_ADMIN',
    status: 'ACTIVE',
    phone: '+250780000001',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'usr-002',
    first_name: 'Test',
    last_name: 'Landlord',
    email: 'landlord@notify.test',
    role: 'LANDLORD',
    status: 'ACTIVE',
    phone: '+250780000002',
    business_name: 'Notify Dev Properties Ltd',
    created_at: '2026-01-10T09:00:00Z',
  },
  {
    id: 'usr-003',
    first_name: 'Test',
    last_name: 'Tenant',
    email: 'tenant@notify.test',
    role: 'TENANT',
    status: 'ACTIVE',
    phone: '+250780000003',
    created_at: '2026-01-15T11:20:00Z',
  },
];

export const MOCK_ADMIN_AUDIT_LOGS = [
  {
    id: 'log-001',
    action: 'USER_LOGIN',
    user_email: 'landlord@notify.test',
    details: 'User authenticated via mock login mode',
    timestamp: '2026-08-13T10:30:00Z',
    ip_address: '127.0.0.1',
  },
  {
    id: 'log-002',
    action: 'INVITATION_CREATED',
    user_email: 'landlord@notify.test',
    details: 'Invitation sent for Unit 102',
    timestamp: '2026-08-10T14:30:00Z',
    ip_address: '127.0.0.1',
  },
  {
    id: 'log-003',
    action: 'SYSTEM_BOOT',
    user_email: 'system',
    details: 'Notify Phase 1 Foundation Service Started',
    timestamp: '2026-08-01T00:00:00Z',
    ip_address: '127.0.0.1',
  },
];

// ==========================================
// MOCK DATA FOR PHASE 3 FINANCIAL PLATFORM
// ==========================================

export const MOCK_INVOICES: any[] = [
  {
    id: 'inv-2026-001',
    invoice_number: 'INV-2026-000001',
    landlord_id: 'mock-lp-001',
    tenant_id: 'mock-tenant-001',
    property_id: 'prop-heights',
    unit_id: 'unit-a102',
    tenancy_id: 'tenancy-101',
    lease_id: 'lease-101',
    invoice_type: 'RENT',
    billing_period_start: '2026-08-01',
    billing_period_end: '2026-08-31',
    issue_date: '2026-08-01',
    due_date: '2026-08-05',
    subtotal: 350000,
    discount: 0,
    late_fee: 0,
    total_amount: 350000,
    amount_paid: 350000,
    balance_due: 0,
    currency: 'RWF',
    status: 'PAID',
    tenant_name: 'Test Tenant',
    property_name: 'Notify Heights',
    unit_number: 'A-102',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'inv-2026-002',
    invoice_number: 'INV-2026-000002',
    landlord_id: 'mock-lp-001',
    tenant_id: 'tenant-102',
    property_id: 'prop-heights',
    unit_id: 'unit-a101',
    tenancy_id: 'tenancy-102',
    lease_id: 'lease-102',
    invoice_type: 'RENT',
    billing_period_start: '2026-08-01',
    billing_period_end: '2026-08-31',
    issue_date: '2026-08-01',
    due_date: '2026-08-05',
    subtotal: 350000,
    discount: 0,
    late_fee: 15000,
    total_amount: 365000,
    amount_paid: 200000,
    balance_due: 165000,
    currency: 'RWF',
    status: 'OVERDUE',
    tenant_name: 'Eric Mugisha',
    property_name: 'Notify Heights',
    unit_number: 'A-101',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'inv-2026-003',
    invoice_number: 'INV-2026-000003',
    landlord_id: 'mock-lp-001',
    tenant_id: 'tenant-103',
    property_id: 'prop-heights',
    unit_id: 'unit-a103',
    tenancy_id: 'tenancy-103',
    lease_id: 'lease-103',
    invoice_type: 'RENT',
    billing_period_start: '2026-08-01',
    billing_period_end: '2026-08-31',
    issue_date: '2026-08-01',
    due_date: '2026-08-05',
    subtotal: 280000,
    discount: 0,
    late_fee: 0,
    total_amount: 280000,
    amount_paid: 280000,
    balance_due: 0,
    currency: 'RWF',
    status: 'PAID',
    tenant_name: 'Divine Uwase',
    property_name: 'Notify Heights',
    unit_number: 'A-103',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'inv-2026-004',
    invoice_number: 'INV-2026-000004',
    landlord_id: 'mock-lp-001',
    tenant_id: 'tenant-107',
    property_id: 'prop-101',
    unit_id: 'unit-101',
    tenancy_id: 'tenancy-104',
    lease_id: 'lease-104',
    invoice_type: 'RENT',
    billing_period_start: '2026-08-01',
    billing_period_end: '2026-08-31',
    issue_date: '2026-08-01',
    due_date: '2026-08-05',
    subtotal: 250000,
    discount: 0,
    late_fee: 0,
    total_amount: 250000,
    amount_paid: 0,
    balance_due: 250000,
    currency: 'RWF',
    status: 'ISSUED',
    tenant_name: 'Claude Nshimyumuremyi',
    property_name: 'Notify Commercial Complex',
    unit_number: '101',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'inv-2026-005',
    invoice_number: 'INV-2026-000005',
    landlord_id: 'mock-lp-001',
    tenant_id: 'tenant-104',
    property_id: 'prop-heights',
    unit_id: 'unit-a201',
    tenancy_id: 'tenancy-105',
    lease_id: 'lease-105',
    invoice_type: 'RENT',
    billing_period_start: '2026-08-01',
    billing_period_end: '2026-08-31',
    issue_date: '2026-08-01',
    due_date: '2026-08-05',
    subtotal: 500000,
    discount: 0,
    late_fee: 20000,
    total_amount: 520000,
    amount_paid: 0,
    balance_due: 520000,
    currency: 'RWF',
    status: 'OVERDUE',
    tenant_name: 'Patrick Bizimana',
    property_name: 'Notify Heights',
    unit_number: 'A-201',
    created_at: '2026-08-01T08:00:00Z',
  },
];

export const MOCK_PAYMENTS: any[] = [
  {
    id: 'pay-2026-001',
    payment_reference: 'PAY-2026-000001',
    transaction_reference: 'MTN-88231920',
    invoice_id: 'inv-2026-001',
    tenancy_id: 'tenancy-101',
    lease_id: 'lease-101',
    landlord_id: 'mock-lp-001',
    tenant_id: 'mock-tenant-001',
    property_id: 'prop-heights',
    unit_id: 'unit-a102',
    amount: 350000,
    currency: 'RWF',
    payment_method: 'MOBILE_MONEY',
    payment_channel: 'ONLINE',
    status: 'COMPLETED',
    paid_at: '2026-08-02T14:22:00Z',
    verified_at: '2026-08-02T14:22:00Z',
    notes: 'Paid via Mobile Money MTN MoMo',
    tenant_name: 'Test Tenant',
    property_name: 'Notify Heights',
    unit_number: 'A-102',
    invoice_number: 'INV-2026-000001',
    created_at: '2026-08-02T14:22:00Z',
  },
  {
    id: 'pay-2026-002',
    payment_reference: 'PAY-2026-000002',
    transaction_reference: 'BK-5529104',
    invoice_id: 'inv-2026-002',
    tenancy_id: 'tenancy-102',
    lease_id: 'lease-102',
    landlord_id: 'mock-lp-001',
    tenant_id: 'tenant-102',
    property_id: 'prop-heights',
    unit_id: 'unit-a101',
    amount: 200000,
    currency: 'RWF',
    payment_method: 'BANK',
    payment_channel: 'OFFLINE',
    status: 'COMPLETED',
    paid_at: '2026-08-06T10:15:00Z',
    verified_at: '2026-08-06T11:00:00Z',
    notes: 'Bank Slip #BK-5529104 - Verified by Landlord',
    tenant_name: 'Eric Mugisha',
    property_name: 'Notify Heights',
    unit_number: 'A-101',
    invoice_number: 'INV-2026-000002',
    created_at: '2026-08-06T10:15:00Z',
  },
  {
    id: 'pay-2026-003',
    payment_reference: 'PAY-2026-000003',
    transaction_reference: 'AIRTEL-773120',
    invoice_id: 'inv-2026-003',
    tenancy_id: 'tenancy-103',
    lease_id: 'lease-103',
    landlord_id: 'mock-lp-001',
    tenant_id: 'tenant-103',
    property_id: 'prop-heights',
    unit_id: 'unit-a103',
    amount: 280000,
    currency: 'RWF',
    payment_method: 'MOBILE_MONEY',
    payment_channel: 'ONLINE',
    status: 'COMPLETED',
    paid_at: '2026-08-03T09:45:00Z',
    verified_at: '2026-08-03T09:45:00Z',
    notes: 'Paid via Airtel Money',
    tenant_name: 'Divine Uwase',
    property_name: 'Notify Heights',
    unit_number: 'A-103',
    invoice_number: 'INV-2026-000003',
    created_at: '2026-08-03T09:45:00Z',
  },
  {
    id: 'pay-2026-004',
    payment_reference: 'PAY-2026-000004',
    transaction_reference: 'CASH-DEP-991',
    invoice_id: 'inv-2026-004',
    tenancy_id: 'tenancy-104',
    lease_id: 'lease-104',
    landlord_id: 'mock-lp-001',
    tenant_id: 'tenant-107',
    property_id: 'prop-101',
    unit_id: 'unit-101',
    amount: 250000,
    currency: 'RWF',
    payment_method: 'CASH',
    payment_channel: 'OFFLINE',
    status: 'AWAITING_VERIFICATION',
    notes: 'Tenant submitted bank deposit slip copy. Awaiting landlord verification.',
    tenant_name: 'Claude Nshimyumuremyi',
    property_name: 'Notify Commercial Complex',
    unit_number: '101',
    invoice_number: 'INV-2026-000004',
    created_at: '2026-08-12T16:30:00Z',
  },
];

export const MOCK_RECEIPTS: any[] = [
  {
    id: 'rct-2026-001',
    receipt_number: 'RCT-2026-000001',
    payment_id: 'pay-2026-001',
    invoice_id: 'inv-2026-001',
    tenant_id: 'mock-tenant-001',
    landlord_id: 'mock-lp-001',
    property_id: 'prop-heights',
    unit_id: 'unit-a102',
    amount: 350000,
    currency: 'RWF',
    issued_at: '2026-08-02T14:22:00Z',
    tenant_name: 'Test Tenant',
    landlord_name: 'Notify Dev Properties Ltd',
    property_name: 'Notify Heights',
    unit_number: 'A-102',
    payment_method: 'MOBILE_MONEY',
  },
  {
    id: 'rct-2026-002',
    receipt_number: 'RCT-2026-000002',
    payment_id: 'pay-2026-002',
    invoice_id: 'inv-2026-002',
    tenant_id: 'tenant-102',
    landlord_id: 'mock-lp-001',
    property_id: 'prop-heights',
    unit_id: 'unit-a101',
    amount: 200000,
    currency: 'RWF',
    issued_at: '2026-08-06T11:00:00Z',
    tenant_name: 'Eric Mugisha',
    landlord_name: 'Notify Dev Properties Ltd',
    property_name: 'Notify Heights',
    unit_number: 'A-101',
    payment_method: 'BANK',
  },
  {
    id: 'rct-2026-003',
    receipt_number: 'RCT-2026-000003',
    payment_id: 'pay-2026-003',
    invoice_id: 'inv-2026-003',
    tenant_id: 'tenant-103',
    landlord_id: 'mock-lp-001',
    property_id: 'prop-heights',
    unit_id: 'unit-a103',
    amount: 280000,
    currency: 'RWF',
    issued_at: '2026-08-03T09:45:00Z',
    tenant_name: 'Divine Uwase',
    landlord_name: 'Notify Dev Properties Ltd',
    property_name: 'Notify Heights',
    unit_number: 'A-103',
    payment_method: 'MOBILE_MONEY',
  },
];

export const MOCK_EXPENSES: any[] = [
  {
    id: 'exp-001',
    landlord_id: 'mock-lp-001',
    property_id: 'prop-heights',
    unit_id: 'unit-a102',
    category: 'MAINTENANCE',
    description: 'Plumbing repair for Unit A-102 bathroom leakage',
    amount: 45000,
    currency: 'RWF',
    expense_date: '2026-08-04',
    vendor: 'Kigali Plumbing Services',
    reference: 'INV-PL-882',
    status: 'RECORDED',
    property_name: 'Notify Heights',
    unit_number: 'A-102',
  },
  {
    id: 'exp-002',
    landlord_id: 'mock-lp-001',
    property_id: 'prop-heights',
    category: 'SECURITY',
    description: 'Monthly security guard service fee',
    amount: 120000,
    currency: 'RWF',
    expense_date: '2026-08-01',
    vendor: 'ISCO Security Ltd',
    reference: 'SEC-2026-08',
    status: 'RECORDED',
    property_name: 'Notify Heights',
  },
  {
    id: 'exp-003',
    landlord_id: 'mock-lp-001',
    property_id: 'prop-101',
    category: 'UTILITIES',
    description: 'Common area electricity & water bills',
    amount: 85000,
    currency: 'RWF',
    expense_date: '2026-08-05',
    vendor: 'WASAC & EUCL',
    reference: 'UTIL-0826',
    status: 'RECORDED',
    property_name: 'Notify Commercial Complex',
  },
];

export const MOCK_LANDLORD_FINANCIALS = {
  expected_rent: 1765000,
  collected_rent: 830000,
  outstanding_rent: 935000,
  overdue_rent: 685000,
  collection_rate: 47.0,
  total_expenses: 250000,
  net_income: 580000,
  currency: 'RWF',
  monthly_trends: [
    { month: 'May', expected: 1700000, collected: 1650000, outstanding: 50000 },
    { month: 'Jun', expected: 1750000, collected: 1700000, outstanding: 50000 },
    { month: 'Jul', expected: 1765000, collected: 1720000, outstanding: 45000 },
    { month: 'Aug', expected: 1765000, collected: 830000, outstanding: 935000 },
  ],
};

export const MOCK_TENANT_FINANCIALS = {
  current_rent: 350000,
  amount_due: 0,
  due_date: '2026-08-05',
  invoice_number: 'INV-2026-000001',
  invoice_id: 'inv-2026-001',
  invoice_status: 'PAID',
  outstanding_balance: 0,
  currency: 'RWF',
};

export const MOCK_NOTIFICATIONS: any[] = [
  {
    id: 'notif-lease-today',
    user_id: 'mock-landlord-001',
    type: 'LEASE_EXPIRY_TODAY',
    title: 'Lease Expiring Today: Samuel Kayiranga (A-104)',
    message: 'The lease for Samuel Kayiranga at Notify Heights, Unit A-104 expires TODAY (August 14, 2026). Recommended Action: Execute signed renewal lease or finalize unit vacancy and security deposit refund.',
    channel: 'IN_APP',
    priority: 'CRITICAL',
    category: 'LEASE_EXPIRY',
    status: 'SENT',
    is_read: false,
    entity_type: 'LEASE',
    entity_id: 'lease-today',
    action_url: '/dashboard/leases',
    action_label: 'Execute Renewal / Handover',
    created_at: '2026-08-14T07:00:00Z',
  },
  {
    id: 'notif-lease-1d',
    user_id: 'mock-landlord-001',
    type: 'LEASE_EXPIRY_1D',
    title: 'Final Day Notice: Lease Expires Tomorrow - Tech Hub Ltd',
    message: 'Lease for Tech Hub Ltd in Unit 201 at Notify Commercial Complex expires tomorrow on August 15, 2026. Recommended Action: Confirm tomorrow\'s walk-through inspection and key return time.',
    channel: 'IN_APP',
    priority: 'CRITICAL',
    category: 'LEASE_EXPIRY',
    status: 'SENT',
    is_read: false,
    entity_type: 'LEASE',
    entity_id: 'lease-1d',
    action_url: '/dashboard/leases',
    action_label: 'Finalize Lease',
    created_at: '2026-08-13T08:00:00Z',
  },
  {
    id: 'notif-lease-2d',
    user_id: 'mock-landlord-001',
    type: 'LEASE_EXPIRY_2D',
    title: 'Critical: Lease Expiring in 2 Days - Jean-Paul Ndayishimiye',
    message: 'Lease for Unit A-203 (Notify Heights) will expire in 2 days on August 16, 2026. Recommended Action: Prepare deposit reconciliation statement and move-out condition report.',
    channel: 'IN_APP',
    priority: 'CRITICAL',
    category: 'LEASE_EXPIRY',
    status: 'SENT',
    is_read: false,
    entity_type: 'LEASE',
    entity_id: 'lease-2d',
    action_url: '/dashboard/leases',
    action_label: 'Resolve Renewal Status',
    created_at: '2026-08-12T08:00:00Z',
  },
  {
    id: 'notif-lease-3d',
    user_id: 'mock-landlord-001',
    type: 'LEASE_EXPIRY_3D',
    title: 'Critical: Lease Expiring in 3 Days - Aline Mutesi',
    message: 'Tenant Aline Mutesi in Unit A-202 at Notify Heights has only 3 days left until lease expiration on August 17, 2026. Recommended Action: Urgent: Finalize renewed contract or schedule final meter reading.',
    channel: 'IN_APP',
    priority: 'CRITICAL',
    category: 'LEASE_EXPIRY',
    status: 'SENT',
    is_read: false,
    entity_type: 'LEASE',
    entity_id: 'lease-3d',
    action_url: '/dashboard/leases',
    action_label: 'Immediate Action Required',
    created_at: '2026-08-11T08:00:00Z',
  },
  {
    id: 'notif-lease-7d',
    user_id: 'mock-landlord-001',
    type: 'LEASE_EXPIRY_7D',
    title: 'Urgent: Lease Expiring in 7 Days (Unit 101 - Claude N.)',
    message: 'Lease for Claude Nshimyumuremyi at Notify Commercial Complex, Unit 101 expires in 7 days on August 21, 2026. Recommended Action: Confirm signing of lease extension or prepare move-out inspection checklist.',
    channel: 'IN_APP',
    priority: 'HIGH',
    category: 'LEASE_EXPIRY',
    status: 'SENT',
    is_read: false,
    entity_type: 'LEASE',
    entity_id: 'lease-7d',
    action_url: '/dashboard/leases',
    action_label: 'Prepare Renewal',
    created_at: '2026-08-07T08:00:00Z',
  },
  {
    id: 'notif-lease-14d',
    user_id: 'mock-landlord-001',
    type: 'LEASE_EXPIRY_14D',
    title: 'Lease Expiring in 14 Days: Eric Mugisha (A-101)',
    message: 'Lease for unit A-101 (Notify Heights) expires in 14 days on August 28, 2026. Recommended Action: Follow up on renewal proposal. If not renewing, schedule prospective tenant viewings.',
    channel: 'IN_APP',
    priority: 'MEDIUM',
    category: 'LEASE_EXPIRY',
    status: 'SENT',
    is_read: true,
    entity_type: 'LEASE',
    entity_id: 'lease-14d',
    action_url: '/dashboard/leases',
    action_label: 'Contact Tenant',
    created_at: '2026-07-31T08:00:00Z',
  },
  {
    id: 'notif-lease-30d',
    user_id: 'mock-landlord-001',
    type: 'LEASE_EXPIRY_30D',
    title: 'Lease Expiring in 30 Days: Notify Heights - A-103',
    message: 'Tenant Divine Uwase in unit A-103 at Notify Heights has a lease expiring on September 13, 2026 (30 days remaining). Recommended Action: Initiate renewal discussion with tenant and send renewal proposal terms.',
    channel: 'IN_APP',
    priority: 'MEDIUM',
    category: 'LEASE_EXPIRY',
    status: 'SENT',
    is_read: true,
    entity_type: 'LEASE',
    entity_id: 'lease-30d',
    action_url: '/dashboard/leases',
    action_label: 'Review Lease & Renew',
    created_at: '2026-07-15T08:00:00Z',
  },
  {
    id: 'notif-p4-001',
    user_id: 'mock-tenant-001',
    type: 'MAINTENANCE_RESOLVED',
    title: 'Issue Marked as Resolved',
    message: 'Landlord marked MR-2026-000002 (Entrance door lock sticking) as resolved. Please review and confirm.',
    channel: 'IN_APP',
    priority: 'MEDIUM',
    category: 'MAINTENANCE',
    status: 'SENT',
    is_read: false,
    entity_type: 'MAINTENANCE',
    entity_id: 'mr-002',
    created_at: '2026-08-12T16:00:00Z',
  },
  {
    id: 'notif-p4-002',
    user_id: 'mock-tenant-001',
    type: 'MAINTENANCE_SCHEDULED',
    title: 'Maintenance Visit Scheduled',
    message: 'Technician Jean-Claude Ndayisaba is scheduled for tomorrow at 10:00 AM for MR-2026-000001.',
    channel: 'IN_APP',
    priority: 'MEDIUM',
    category: 'MAINTENANCE',
    status: 'SENT',
    is_read: false,
    entity_type: 'MAINTENANCE',
    entity_id: 'mr-001',
    created_at: '2026-08-13T08:30:00Z',
  },
  {
    id: 'notif-001',
    user_id: 'mock-tenant-001',
    type: 'PAYMENT_RECEIVED',
    title: 'Payment Confirmed & Receipt Generated',
    message: 'Your payment of RWF 350,000 for invoice INV-2026-000001 was successfully processed. Receipt #RCT-2026-000001 is available.',
    channel: 'IN_APP',
    priority: 'LOW',
    category: 'PAYMENT',
    status: 'SENT',
    is_read: true,
    reference_type: 'RECEIPT',
    reference_id: 'rct-2026-001',
    created_at: '2026-08-02T14:22:00Z',
  },
  {
    id: 'notif-002',
    user_id: 'mock-tenant-001',
    type: 'RENT_DUE',
    title: 'Monthly Rent Invoice Issued',
    message: 'Your rent invoice INV-2026-000001 for August 2026 (RWF 350,000) is ready.',
    channel: 'IN_APP',
    priority: 'HIGH',
    category: 'PAYMENT',
    status: 'READ',
    is_read: true,
    reference_type: 'INVOICE',
    reference_id: 'inv-2026-001',
    created_at: '2026-08-01T08:00:00Z',
  },
];

export const MOCK_NOTIFICATION_PREFERENCES = {
  user_id: 'mock-lp-001',
  lease_expiry_in_app: true,
  lease_expiry_email: true,
  lease_expiry_sms: false,
  lease_expiry_whatsapp: false,

  payment_in_app: true,
  payment_email: true,
  payment_sms: true,
  payment_whatsapp: false,

  maintenance_in_app: true,
  maintenance_email: true,
  maintenance_sms: false,
  maintenance_whatsapp: false,

  complaints_in_app: true,
  complaints_email: true,
  complaints_sms: false,
  complaints_whatsapp: false,

  system_in_app: true,
  system_email: false,
  system_sms: false,
  system_whatsapp: false,
};

export const MOCK_DELIVERY_LOGS: any[] = [
  {
    id: 'log-001',
    notification_id: 'notif-lease-today',
    user_id: 'mock-lp-001',
    channel: 'EMAIL',
    recipient: 'landlord@notify.test',
    subject: '[Notify Kigali] Lease Expiring Today: Samuel Kayiranga (A-104)',
    status: 'SENT',
    metadata_info: JSON.stringify({ tenant_name: 'Samuel Kayiranga', unit_number: 'A-104', days_remaining: 0 }),
    created_at: '2026-08-14T07:00:05Z',
  },
  {
    id: 'log-002',
    notification_id: 'notif-lease-1d',
    user_id: 'mock-lp-001',
    channel: 'EMAIL',
    recipient: 'landlord@notify.test',
    subject: '[Notify Kigali] Final Day Notice: Lease Expires Tomorrow - Tech Hub Ltd',
    status: 'SENT',
    metadata_info: JSON.stringify({ tenant_name: 'Tech Hub Ltd', unit_number: '201', days_remaining: 1 }),
    created_at: '2026-08-13T08:00:05Z',
  },
  {
    id: 'log-003',
    notification_id: 'notif-lease-3d',
    user_id: 'mock-lp-001',
    channel: 'EMAIL',
    recipient: 'landlord@notify.test',
    subject: '[Notify Kigali] Critical: Lease Expiring in 3 Days - Aline Mutesi',
    status: 'SENT',
    metadata_info: JSON.stringify({ tenant_name: 'Aline Mutesi', unit_number: 'A-202', days_remaining: 3 }),
    created_at: '2026-08-11T08:00:05Z',
  },
  {
    id: 'log-004',
    notification_id: 'notif-lease-7d',
    user_id: 'mock-lp-001',
    channel: 'EMAIL',
    recipient: 'landlord@notify.test',
    subject: '[Notify Kigali] Urgent: Lease Expiring in 7 Days (Unit 101 - Claude N.)',
    status: 'SENT',
    metadata_info: JSON.stringify({ tenant_name: 'Claude N.', unit_number: '101', days_remaining: 7 }),
    created_at: '2026-08-07T08:00:05Z',
  },
];

export const MOCK_WORKERS: any[] = [
  {
    id: 'worker-001',
    landlord_id: 'mock-lp-001',
    name: 'Jean-Claude Ndayisaba',
    phone: '+250788112233',
    specialization: 'PLUMBER',
    status: 'ACTIVE',
    notes: 'Certified plumbing technician, available Mon-Sat',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'worker-002',
    landlord_id: 'mock-lp-001',
    name: 'Emmanuel Habimana',
    phone: '+250788445566',
    specialization: 'ELECTRICIAN',
    status: 'ACTIVE',
    notes: 'Master certified high voltage & lighting technician',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'worker-003',
    landlord_id: 'mock-lp-001',
    name: 'Patrick Mugisha',
    phone: '+250788778899',
    specialization: 'GENERAL',
    status: 'ACTIVE',
    notes: 'General contractor, carpentry, lock & structural repairs',
    created_at: '2026-08-01T08:00:00Z',
  },
];

export const MOCK_MAINTENANCE_REQUESTS: any[] = [
  {
    id: 'mr-001',
    request_number: 'MR-2026-000001',
    tenant_id: 'mock-tp-001',
    landlord_id: 'mock-lp-001',
    property_id: 'prop-101',
    unit_id: 'unit-101',
    tenancy_id: 'tenancy-001',
    title: 'Water leak under washbasin counter',
    description: 'Water is dripping steadily from the flex hose connector under the washbasin. Bucket is filling up every 4 hours.',
    category: 'PLUMBING',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    assigned_to: 'Jean-Claude Ndayisaba',
    scheduled_date: '2026-08-14T10:00:00Z',
    scheduled_time: '10:00 AM',
    estimated_cost: 25000,
    actual_cost: 0,
    currency: 'RWF',
    tenant_name: 'Test Tenant',
    property_name: 'Notify Dev Center',
    unit_number: '101',
    attachments: [
      {
        id: 'att-001',
        maintenance_request_id: 'mr-001',
        file_path: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format&fit=crop&q=80',
        file_name: 'leak_photo.jpg',
        mime_type: 'image/jpeg',
        size: 1048576,
        uploaded_by: 'mock-tenant-001',
        created_at: '2026-08-12T10:00:00Z',
      },
    ],
    comments: [
      {
        id: 'mc-001',
        maintenance_request_id: 'mr-001',
        user_id: 'mock-tenant-001',
        author_name: 'Test Tenant',
        author_role: 'TENANT',
        message: 'Please send technician in the morning if possible, our store opens at 9:00 AM.',
        created_at: '2026-08-12T10:05:00Z',
      },
      {
        id: 'mc-002',
        maintenance_request_id: 'mr-001',
        user_id: 'mock-landlord-001',
        author_name: 'Notify Dev Properties Ltd',
        author_role: 'LANDLORD',
        message: 'Acknowledged. Jean-Claude will arrive tomorrow at 10:00 AM with replacement seals.',
        created_at: '2026-08-12T14:30:00Z',
      },
    ],
    created_at: '2026-08-12T09:45:00Z',
    updated_at: '2026-08-12T14:30:00Z',
  },
  {
    id: 'mr-002',
    request_number: 'MR-2026-000002',
    tenant_id: 'mock-tp-001',
    landlord_id: 'mock-lp-001',
    property_id: 'prop-101',
    unit_id: 'unit-101',
    tenancy_id: 'tenancy-001',
    title: 'Entrance security lock cylinder sticking',
    description: 'Key gets stuck when turning to deadbolt position. Needs cylinder replacement.',
    category: 'SECURITY',
    priority: 'MEDIUM',
    status: 'RESOLVED',
    assigned_to: 'Patrick Mugisha',
    scheduled_date: '2026-08-11T14:00:00Z',
    scheduled_time: '02:00 PM',
    estimated_cost: 35000,
    actual_cost: 35000,
    currency: 'RWF',
    landlord_notes: 'Replaced lock cylinder with a brand new Yale High Security deadbolt. Tested 5 times smoothly.',
    tenant_name: 'Test Tenant',
    property_name: 'Notify Dev Center',
    unit_number: '101',
    attachments: [],
    comments: [
      {
        id: 'mc-003',
        maintenance_request_id: 'mr-002',
        user_id: 'mock-landlord-001',
        author_name: 'Notify Dev Properties Ltd',
        author_role: 'LANDLORD',
        message: 'Work completed. Please verify that all shop keys turn smoothly.',
        created_at: '2026-08-12T16:00:00Z',
      },
    ],
    acknowledged_at: '2026-08-10T10:00:00Z',
    scheduled_at: '2026-08-10T15:00:00Z',
    resolved_at: '2026-08-12T16:00:00Z',
    created_at: '2026-08-10T08:30:00Z',
    updated_at: '2026-08-12T16:00:00Z',
  },
  {
    id: 'mr-003',
    request_number: 'MR-2026-000003',
    tenant_id: 'mock-tp-001',
    landlord_id: 'mock-lp-001',
    property_id: 'prop-101',
    unit_id: 'unit-101',
    tenancy_id: 'tenancy-001',
    title: 'Fluorescent tube fixture replacement',
    description: 'Overhead display lights are buzzing and blinking.',
    category: 'ELECTRICAL',
    priority: 'LOW',
    status: 'CLOSED',
    assigned_to: 'Emmanuel Habimana',
    estimated_cost: 15000,
    actual_cost: 15000,
    currency: 'RWF',
    tenant_notes: 'Confirmed fixed. New daylight LED tubes work wonderfully.',
    tenant_name: 'Test Tenant',
    property_name: 'Notify Dev Center',
    unit_number: '101',
    attachments: [],
    comments: [],
    acknowledged_at: '2026-08-03T09:00:00Z',
    resolved_at: '2026-08-05T11:00:00Z',
    closed_at: '2026-08-06T10:00:00Z',
    created_at: '2026-08-02T14:00:00Z',
    updated_at: '2026-08-06T10:00:00Z',
  },
  {
    id: 'mr-004',
    request_number: 'MR-2026-000004',
    tenant_id: 'mock-tp-001',
    landlord_id: 'mock-lp-001',
    property_id: 'prop-101',
    unit_id: 'unit-101',
    tenancy_id: 'tenancy-001',
    title: 'Ceiling water seepage near exterior AC unit',
    description: 'Noticed water seepage stains expanding on drywall ceiling following heavy afternoon downpour.',
    category: 'STRUCTURAL',
    priority: 'URGENT',
    status: 'SUBMITTED',
    estimated_cost: 0,
    actual_cost: 0,
    currency: 'RWF',
    tenant_name: 'Test Tenant',
    property_name: 'Notify Dev Center',
    unit_number: '101',
    attachments: [],
    comments: [],
    created_at: '2026-08-13T15:00:00Z',
    updated_at: '2026-08-13T15:00:00Z',
  },
];

export const MOCK_COMPLAINTS: any[] = [
  {
    id: 'cmp-001',
    complaint_number: 'CMP-2026-000001',
    tenant_id: 'mock-tp-001',
    landlord_id: 'mock-lp-001',
    property_id: 'prop-101',
    unit_id: 'unit-101',
    tenancy_id: 'tenancy-001',
    subject: 'Early morning loading truck engine idling noise',
    description: 'Heavy delivery trucks are idling their diesel engines right behind our unit windows starting at 5:00 AM.',
    category: 'NOISE',
    priority: 'MEDIUM',
    status: 'UNDER_REVIEW',
    landlord_response: 'We have contacted the commercial complex logistics manager to restrict delivery bay engine idling before 7:30 AM.',
    tenant_name: 'Test Tenant',
    property_name: 'Notify Dev Center',
    unit_number: '101',
    comments: [
      {
        id: 'cc-001',
        complaint_id: 'cmp-001',
        user_id: 'mock-tenant-001',
        author_name: 'Test Tenant',
        author_role: 'TENANT',
        message: 'It happened again this Tuesday morning. Thank you for addressing it.',
        created_at: '2026-08-11T12:00:00Z',
      },
      {
        id: 'cc-002',
        complaint_id: 'cmp-001',
        user_id: 'mock-landlord-001',
        author_name: 'Notify Dev Properties Ltd',
        author_role: 'LANDLORD',
        message: 'Security guard post has been instructed to turn away pre-7:30 AM idling vehicles.',
        created_at: '2026-08-12T09:00:00Z',
      },
    ],
    acknowledged_at: '2026-08-10T09:00:00Z',
    created_at: '2026-08-09T14:00:00Z',
    updated_at: '2026-08-12T09:00:00Z',
  },
  {
    id: 'cmp-002',
    complaint_number: 'CMP-2026-000002',
    tenant_id: 'mock-tp-001',
    landlord_id: 'mock-lp-001',
    property_id: 'prop-101',
    unit_id: 'unit-101',
    tenancy_id: 'tenancy-001',
    subject: 'Corridor emergency lighting battery low indicator',
    description: 'The backup battery beeper on the 1st floor corridor exit sign is beeping intermittently.',
    category: 'SECURITY',
    priority: 'HIGH',
    status: 'RESOLVED',
    landlord_response: 'Battery pack replaced and test button verified with facility engineer.',
    tenant_name: 'Test Tenant',
    property_name: 'Notify Dev Center',
    unit_number: '101',
    comments: [],
    acknowledged_at: '2026-08-07T08:00:00Z',
    resolved_at: '2026-08-09T11:00:00Z',
    created_at: '2026-08-06T15:00:00Z',
    updated_at: '2026-08-09T11:00:00Z',
  },
];

export const MOCK_MESSAGES: any[] = [
  {
    id: 'msg-001',
    sender_id: 'mock-tenant-001',
    recipient_id: 'mock-landlord-001',
    sender_role: 'TENANT',
    sender_name: 'Test Tenant',
    recipient_name: 'Test Landlord',
    property_id: 'prop-101',
    property_name: 'Notify Dev Center',
    unit_id: 'unit-101',
    unit_number: '101',
    tenancy_id: 'tenancy-001',
    message_type: 'GENERAL',
    content: 'Hello! I wanted to check what the building policy is regarding weekend visitor parking access for unit 101?',
    is_read: true,
    created_at: '2026-08-10T08:15:00Z',
  },
  {
    id: 'msg-002',
    sender_id: 'mock-landlord-001',
    recipient_id: 'mock-tenant-001',
    sender_role: 'LANDLORD',
    sender_name: 'Test Landlord',
    recipient_name: 'Test Tenant',
    property_id: 'prop-101',
    property_name: 'Notify Dev Center',
    unit_id: 'unit-101',
    unit_number: '101',
    tenancy_id: 'tenancy-001',
    message_type: 'GENERAL',
    content: 'Hello! Weekend visitors can park in bays P12 through P18 free of charge between 8:00 AM and 10:00 PM. Just display the visitor tag on the dashboard.',
    is_read: true,
    created_at: '2026-08-10T08:45:00Z',
  },
  {
    id: 'msg-003',
    sender_id: 'mock-tenant-001',
    recipient_id: 'mock-landlord-001',
    sender_role: 'TENANT',
    sender_name: 'Test Tenant',
    recipient_name: 'Test Landlord',
    property_id: 'prop-101',
    property_name: 'Notify Dev Center',
    unit_id: 'unit-101',
    unit_number: '101',
    tenancy_id: 'tenancy-001',
    message_type: 'MAINTENANCE',
    content: 'Water is dripping steadily from the flex hose connector under the washbasin. Bucket is filling up every 4 hours.',
    maintenance_request_id: 'mr-001',
    maintenance_title: 'Water leak under washbasin counter',
    maintenance_category: 'PLUMBING',
    maintenance_priority: 'HIGH',
    maintenance_status: 'IN_PROGRESS',
    attachment_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format&fit=crop&q=80',
    attachment_name: 'leak_photo.jpg',
    is_read: true,
    created_at: '2026-08-12T09:45:00Z',
  },
  {
    id: 'msg-004',
    sender_id: 'mock-landlord-001',
    recipient_id: 'mock-tenant-001',
    sender_role: 'LANDLORD',
    sender_name: 'Test Landlord',
    recipient_name: 'Test Tenant',
    property_id: 'prop-101',
    property_name: 'Notify Dev Center',
    unit_id: 'unit-101',
    unit_number: '101',
    tenancy_id: 'tenancy-001',
    message_type: 'GENERAL',
    content: 'Acknowledged! Jean-Claude our certified plumber has been scheduled to inspect and replace the connector tomorrow at 10:00 AM.',
    is_read: true,
    created_at: '2026-08-12T14:30:00Z',
  },
  {
    id: 'msg-005',
    sender_id: 'mock-tenant-001',
    recipient_id: 'mock-landlord-001',
    sender_role: 'TENANT',
    sender_name: 'Test Tenant',
    recipient_name: 'Test Landlord',
    property_id: 'prop-101',
    property_name: 'Notify Dev Center',
    unit_id: 'unit-101',
    unit_number: '101',
    tenancy_id: 'tenancy-001',
    message_type: 'MAINTENANCE',
    content: 'Noticed water seepage stains expanding on drywall ceiling following heavy afternoon downpour.',
    maintenance_request_id: 'mr-004',
    maintenance_title: 'Ceiling water seepage near exterior AC unit',
    maintenance_category: 'STRUCTURAL',
    maintenance_priority: 'URGENT',
    maintenance_status: 'SUBMITTED',
    is_read: false,
    created_at: '2026-08-13T15:00:00Z',
  },
];

export const MOCK_BANK_ACCOUNTS = [
  {
    id: 'ba-001',
    bank_name: 'Bank of Kigali (BK)',
    account_name: 'Notify Dev Properties Ltd - Operational',
    account_number: '00040-0694821-45',
    currency: 'RWF',
    is_primary: true,
  },
  {
    id: 'ba-002',
    bank_name: 'I&M Bank Rwanda',
    account_name: 'Notify Dev Properties Ltd - Rental Collection',
    account_number: '2000-14920-01',
    currency: 'RWF',
    is_primary: false,
  },
  {
    id: 'ba-003',
    bank_name: 'MTN Mobile Money Merchant',
    account_name: 'Notify Properties MoMo Pay',
    account_number: 'MOMO-894210',
    currency: 'RWF',
    is_primary: false,
  },
];

export const MOCK_BANK_STATEMENTS: any[] = [
  {
    id: 'stmt-001',
    file_name: 'BK_Rental_Collection_Aug_2026.csv',
    file_type: 'CSV',
    file_size: 48200,
    uploaded_at: '2026-08-15T08:30:00Z',
    period_start: '2026-08-01',
    period_end: '2026-08-31',
    total_transactions_count: 14,
    matched_count: 11,
    unmatched_count: 2,
    duplicate_count: 1,
    total_incoming_amount: 4250000,
    matched_amount: 3750000,
    status: 'COMPLETED',
    notes: 'Bank of Kigali e-statement auto-import',
  },
  {
    id: 'stmt-002',
    file_name: 'MTN_MoMo_Settlement_Aug_2026.xlsx',
    file_type: 'XLSX',
    file_size: 26400,
    uploaded_at: '2026-08-10T14:15:00Z',
    period_start: '2026-08-01',
    period_end: '2026-08-10',
    total_transactions_count: 8,
    matched_count: 7,
    unmatched_count: 1,
    duplicate_count: 0,
    total_incoming_amount: 2100000,
    matched_amount: 1950000,
    status: 'COMPLETED',
    notes: 'MTN MoMo Pay merchant settlement statement',
  },
];

export const MOCK_BANK_TRANSACTIONS: any[] = [
  {
    id: 'txn-001',
    statement_id: 'stmt-001',
    transaction_reference: 'BK-20260802-89410',
    transaction_date: '2026-08-02',
    amount: 450000,
    payer_name: 'Aline Mukamana',
    description: 'BK TRF: ALINE MUKAMANA - RENT UNIT 101 INV-2026-0001',
    matching_status: 'MATCHED',
    confidence_score: 0.98,
    suggested_tenant_id: 'mock-tenant-001',
    suggested_invoice_id: 'inv-001',
    match_method: 'INVOICE_REF_MATCH',
  },
  {
    id: 'txn-002',
    statement_id: 'stmt-001',
    transaction_reference: 'BK-20260803-11203',
    transaction_date: '2026-08-03',
    amount: 600000,
    payer_name: 'Jean Bosco Mugisha',
    description: 'FT FRM JEAN BOSCO MUGISHA REF NOTIFY-INV-2026-0002',
    matching_status: 'MATCHED',
    confidence_score: 0.98,
    suggested_tenant_id: 'mock-tenant-002',
    suggested_invoice_id: 'inv-002',
    match_method: 'INVOICE_REF_MATCH',
  },
  {
    id: 'txn-003',
    statement_id: 'stmt-001',
    transaction_reference: 'BK-20260804-45091',
    transaction_date: '2026-08-04',
    amount: 350000,
    payer_name: 'Claudine Uwimana',
    description: 'MOMO FROM 0788123456 CLAUDINE UWIMANA RENT UNIT 103',
    matching_status: 'MATCHED',
    confidence_score: 0.95,
    suggested_tenant_id: 'mock-tenant-003',
    suggested_invoice_id: 'inv-003',
    match_method: 'EXACT_NAME_AMOUNT_MATCH',
  },
  {
    id: 'txn-004',
    statement_id: 'stmt-001',
    transaction_reference: 'BK-20260805-77821',
    transaction_date: '2026-08-05',
    amount: 350000,
    payer_name: 'Emmanuel Habimana',
    description: 'BK TRF: EMMANUEL HABIMANA PARTIAL AUGUST RENT',
    matching_status: 'NEEDS_REVIEW',
    confidence_score: 0.75,
    suggested_tenant_id: 'mock-tenant-004',
    suggested_invoice_id: 'inv-004',
    match_method: 'PARTIAL_PAYMENT_MATCH',
  },
  {
    id: 'txn-005',
    statement_id: 'stmt-001',
    transaction_reference: 'BK-20260806-99014',
    transaction_date: '2026-08-06',
    amount: 280000,
    payer_name: 'Eric Rutayisire',
    description: 'DIRECT DEPOSIT ERIC RUTAYISIRE',
    matching_status: 'NEEDS_REVIEW',
    confidence_score: 0.65,
    suggested_tenant_id: 'mock-tenant-005',
    suggested_invoice_id: 'inv-005',
    match_method: 'NAME_ONLY_MATCH',
  },
  {
    id: 'txn-006',
    statement_id: 'stmt-001',
    transaction_reference: 'BK-20260808-33418',
    transaction_date: '2026-08-08',
    amount: 500000,
    payer_name: 'Kigali Logistics Hub Ltd',
    description: 'INTER-BANK TRF KIGALI LOGISTICS HUB LTD TRF-0912',
    matching_status: 'UNMATCHED',
    confidence_score: 0.0,
    match_method: 'UNMATCHED',
  },
];



